plugins {
    id 'java-library'
    id 'groovy'
    id 'maven-publish'
    id 'signing'
    id 'eclipse'
    id 'idea'
    alias libs.plugins.grace.doc
    alias libs.plugins.gradle.nexus.publish
    alias libs.plugins.gradle.test.retry
}

ext.'signing.keyId' = rootProject.hasProperty('signing.keyId') ? rootProject.getProperty('signing.keyId') : System.getenv('SIGNING_KEY')
ext.'signing.password' = rootProject.hasProperty('signing.password') ? rootProject.getProperty('signing.password') : System.getenv('SIGNING_PASSPHRASE')
ext.'signing.secretKeyRingFile' = rootProject.hasProperty('signing.secretKeyRingFile') ? rootProject.getProperty('signing.secretKeyRingFile') : "${System.properties['user.home']}${File.separator}.gnupg${File.separator}secring.gpg"
ext.isReleaseVersion = !projectVersion.endsWith('SNAPSHOT')

version = project.projectVersion
group = 'org.graceframework.async'

repositories {
    mavenCentral()
    if (project.projectVersion.endsWith('-SNAPSHOT')) {
        maven {
            name = 'Maven Central Portal Snapshots'
            url = 'https://central.sonatype.com/repository/maven-snapshots/'

            content {
                includeGroupAndSubgroups 'org.graceframework'
            }
            mavenContent {
                snapshotsOnly()
            }
        }
    }
}

configurations {
    documentation
}

dependencies {
    documentation libs.javaparser
    documentation libs.groovy.core
}

tasks.withType(Test) {
    useJUnitPlatform()
    testLogging {
        showStandardStreams = true
        exceptionFormat = 'full'
    }
    configure {
        retry {
            maxRetries = 2
            maxFailures = 20
            failOnPassedAfterRetry = true
        }
    }
}

def cleanTask = project.tasks.findByName('clean')
if (cleanTask == null) {
    task clean(type: Delete) {
        delete(buildDir)
    }
}
else {
    cleanTask.doLast {
        ant.delete(dir: 'build/docs')
    }
}

tasks.withType(Groovydoc) {
    group = 'Documentation'
    docTitle = "Grace Async Framework - ${project.version}"
    destinationDir = project.file('build/docs/manual/api')
    def files = []
    project.rootProject.subprojects
            .findAll { !it.name != 'docs' && !it.name.startsWith('examples') }
            .each { subproject ->
                if(subproject.file('src/main/groovy').exists()) {
                    files += subproject.files('src/main/groovy')
                }
                if(subproject.file('src/main/java').exists()) {
                    files += subproject.files('src/main/java')
                }
            }
    if (project.file('src/main/groovy').exists()) {
        files += project.files('src/main/groovy')
    }
    source = files
    classpath += configurations.documentation
}

docs {
    // dependsOn groovydoc
    sourceDir = project.file('src/main/docs')
}

nexusPublishing {
    repositories {
        sonatype {
            def mavenUser = System.getenv('MAVEN_CENTRAL_USER') ?: project.hasProperty('mavenCentralUsername') ? project.mavenCentralUsername : ''
            def mavenPass = System.getenv('MAVEN_CENTRAL_PASSWORD') ?: project.hasProperty('mavenCentralPassword') ? project.mavenCentralPassword : ''
            nexusUrl = uri('https://ossrh-staging-api.central.sonatype.com/service/local/')
            snapshotRepositoryUrl = uri('https://central.sonatype.com/repository/maven-snapshots/')
            username = mavenUser
            password = mavenPass
        }
    }
}
