plugins {
    id "eclipse"
    id "idea"
    id "groovy"
    id "org.graceframework.grace-app"
    id "org.graceframework.asset-pipeline" version '7.1.0-RC1'
    id "org.graceframework.grace-gsp"
    id "org.graceframework.grace-json"
}

group = "org.graceframework.examples"

repositories {
    mavenCentral()
}

configurations {
    developmentOnly
}

dependencies {
    developmentOnly "org.springframework.boot:spring-boot-devtools"
    console "org.graceframework:grace-console"
    implementation "org.graceframework:grace-boot-async"
    implementation "org.graceframework:grace-boot-cache"
    implementation "org.graceframework:grace-boot-events"
    implementation "org.graceframework:grace-boot-hibernate"
    implementation "org.graceframework:grace-boot-logging"
    implementation "org.graceframework:grace-boot-persistence"
    implementation "org.graceframework:grace-boot-plugin"
    implementation "org.graceframework:grace-boot-validation"
    implementation "org.graceframework:grace-boot-web"
    implementation "org.graceframework:grace-plugin-database-migration"
    implementation "org.graceframework:grace-plugin-gsp"
    implementation "org.graceframework:grace-plugin-management"
    implementation "org.graceframework:grace-plugin-services"
    implementation "org.graceframework:grace-plugin-taglibs"
    implementation "org.graceframework:grace-views-json"
    profile "org.graceframework.profiles:web"
    runtimeOnly "com.h2database:h2"
    runtimeOnly "org.graceframework.plugins:asset-pipeline-plugin"
    testImplementation "org.graceframework:grace-boot-test"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.withType(GroovyCompile) {
    configure(groovyOptions) {
        forkOptions.jvmArgs = ['-Xmx1024m']
    }
}

tasks.withType(Test) {
    useJUnitPlatform()
}
