dependencies {
    api project(":grace-events-core")
    api "jakarta.annotation:jakarta.annotation-api:$jakartaAnnotationVersion"
    compileOnly "org.graceframework:grace-datastore-core:$gormVersion", {
        transitive = false
    }
    compileOnly "org.graceframework:grace-datastore-gorm:$gormVersion", {
        transitive = false
    }

    testRuntimeOnly "org.springframework:spring-aop:$springVersion"
    testRuntimeOnly "org.springframework:spring-expression:$springVersion"
    testImplementation "org.graceframework:grace-datastore-gorm-test:$gormVersion", {
        exclude group:'org.graceframework', module:'grace-datastore-gorm-validation'
    }
}